-- Mantém Hora Extra e Mudança de Escala leves sem perder o histórico.
-- A preparação copia os registros antigos para uma área de arquivo. A remoção
-- da base operacional fica em uma etapa separada, executada somente depois da
-- conferência e da disponibilização da exportação.

CREATE TABLE IF NOT EXISTS public.operational_archives (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  worksite_id uuid NOT NULL REFERENCES public.worksites(id),
  cutoff_date date NOT NULL,
  status text NOT NULL DEFAULT 'prepared'
    CHECK (status IN ('prepared', 'finalized', 'cancelled')),
  overtime_count integer NOT NULL DEFAULT 0,
  scale_change_count integer NOT NULL DEFAULT 0,
  prepared_by uuid REFERENCES auth.users(id),
  prepared_at timestamptz NOT NULL DEFAULT now(),
  finalized_by uuid REFERENCES auth.users(id),
  finalized_at timestamptz,
  CONSTRAINT operational_archives_worksite_cutoff_key UNIQUE (worksite_id, cutoff_date)
);

CREATE TABLE IF NOT EXISTS public.operational_archive_rows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archive_id uuid NOT NULL REFERENCES public.operational_archives(id) ON DELETE CASCADE,
  worksite_id uuid NOT NULL REFERENCES public.worksites(id),
  source_type text NOT NULL CHECK (source_type IN ('overtime', 'scale_change')),
  source_id uuid NOT NULL,
  record_date date NOT NULL,
  payload jsonb NOT NULL,
  archived_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT operational_archive_rows_source_key UNIQUE (source_type, source_id)
);

CREATE INDEX IF NOT EXISTS operational_archives_worksite_date_idx
  ON public.operational_archives (worksite_id, cutoff_date DESC);
CREATE INDEX IF NOT EXISTS operational_archive_rows_archive_type_date_idx
  ON public.operational_archive_rows (archive_id, source_type, record_date DESC);
CREATE INDEX IF NOT EXISTS operational_archive_rows_worksite_date_idx
  ON public.operational_archive_rows (worksite_id, record_date DESC);

-- Índices que atendem o padrão real das telas: obra + período + status.
CREATE INDEX IF NOT EXISTS overtime_worksite_date_status_idx
  ON public.overtime_requests (worksite_id, overtime_date DESC, status);
CREATE INDEX IF NOT EXISTS overtime_worksite_requester_date_idx
  ON public.overtime_requests (worksite_id, requester_user_id, overtime_date DESC);
CREATE INDEX IF NOT EXISTS scheduled_transport_worksite_date_status_idx
  ON public.scheduled_transport_requests (worksite_id, transport_date DESC, status);

ALTER TABLE public.operational_archives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operational_archive_rows ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.operational_archives FROM anon, authenticated;
REVOKE ALL ON public.operational_archive_rows FROM anon, authenticated;
GRANT ALL ON public.operational_archives TO service_role;
GRANT ALL ON public.operational_archive_rows TO service_role;

CREATE OR REPLACE FUNCTION public.operational_history_cutoff(_reference_date date DEFAULT current_date)
RETURNS date
LANGUAGE sql
IMMUTABLE
AS $function$
  SELECT (_reference_date - (extract(isodow FROM _reference_date)::integer - 1) - 28)::date;
$function$;

CREATE OR REPLACE FUNCTION public.prepare_operational_archive(
  _worksite_id uuid,
  _cutoff_date date DEFAULT public.operational_history_cutoff(current_date)
)
RETURNS TABLE (
  archive_id uuid,
  overtime_count integer,
  scale_change_count integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_archive_id uuid;
  v_overtime_count integer;
  v_scale_count integer;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'Somente administradores podem preparar arquivos históricos.';
  END IF;

  IF NOT public.can_access_worksite(auth.uid(), _worksite_id) THEN
    RAISE EXCEPTION 'O administrador não possui acesso a esta obra.';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.operational_archives
    WHERE worksite_id = _worksite_id AND cutoff_date = _cutoff_date AND status = 'finalized'
  ) THEN
    RAISE EXCEPTION 'Este período já foi arquivado e finalizado.';
  END IF;

  INSERT INTO public.operational_archives (
    worksite_id, cutoff_date, status, prepared_by, prepared_at
  ) VALUES (
    _worksite_id, _cutoff_date, 'prepared', auth.uid(), now()
  )
  ON CONFLICT (worksite_id, cutoff_date) DO UPDATE
    SET status = 'prepared', prepared_by = auth.uid(), prepared_at = now(),
        finalized_by = NULL, finalized_at = NULL
  RETURNING id INTO v_archive_id;

  INSERT INTO public.operational_archive_rows (
    archive_id, worksite_id, source_type, source_id, record_date, payload
  )
  SELECT v_archive_id, r.worksite_id, 'overtime', r.id, r.overtime_date, to_jsonb(r)
  FROM public.overtime_requests r
  WHERE r.worksite_id = _worksite_id
    AND r.overtime_date < _cutoff_date
    AND r.status IN ('approved', 'rejected', 'cancelled')
  ON CONFLICT (source_type, source_id) DO UPDATE
    SET archive_id = excluded.archive_id,
        worksite_id = excluded.worksite_id,
        record_date = excluded.record_date,
        payload = excluded.payload,
        archived_at = now();

  INSERT INTO public.operational_archive_rows (
    archive_id, worksite_id, source_type, source_id, record_date, payload
  )
  SELECT v_archive_id, r.worksite_id, 'scale_change', r.id, r.transport_date, to_jsonb(r)
  FROM public.scheduled_transport_requests r
  WHERE r.worksite_id = _worksite_id
    AND r.transport_date < _cutoff_date
  ON CONFLICT (source_type, source_id) DO UPDATE
    SET archive_id = excluded.archive_id,
        worksite_id = excluded.worksite_id,
        record_date = excluded.record_date,
        payload = excluded.payload,
        archived_at = now();

  SELECT count(*)::integer INTO v_overtime_count
  FROM public.operational_archive_rows
  WHERE archive_id = v_archive_id AND source_type = 'overtime';

  SELECT count(*)::integer INTO v_scale_count
  FROM public.operational_archive_rows
  WHERE archive_id = v_archive_id AND source_type = 'scale_change';

  UPDATE public.operational_archives
  SET overtime_count = v_overtime_count,
      scale_change_count = v_scale_count
  WHERE id = v_archive_id;

  RETURN QUERY SELECT v_archive_id, v_overtime_count, v_scale_count;
END;
$function$;

REVOKE ALL ON FUNCTION public.prepare_operational_archive(uuid, date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.prepare_operational_archive(uuid, date) TO authenticated;

CREATE OR REPLACE FUNCTION public.finalize_operational_archive(_archive_id uuid)
RETURNS TABLE (
  overtime_deleted integer,
  scale_change_deleted integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_archive public.operational_archives%ROWTYPE;
  v_overtime integer;
  v_scale integer;
BEGIN
  SELECT * INTO v_archive
  FROM public.operational_archives
  WHERE id = _archive_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Arquivo histórico não encontrado.';
  END IF;
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'Somente administradores podem finalizar arquivos históricos.';
  END IF;
  IF NOT public.can_access_worksite(auth.uid(), v_archive.worksite_id) THEN
    RAISE EXCEPTION 'O administrador não possui acesso a esta obra.';
  END IF;
  IF v_archive.status <> 'prepared' THEN
    RAISE EXCEPTION 'Somente arquivos preparados podem ser finalizados.';
  END IF;

  -- Se qualquer linha mudou desde a preparação, a transação inteira é cancelada.
  IF EXISTS (
    SELECT 1
    FROM public.operational_archive_rows ar
    JOIN public.overtime_requests r ON r.id = ar.source_id
    WHERE ar.archive_id = _archive_id
      AND ar.source_type = 'overtime'
      AND to_jsonb(r) IS DISTINCT FROM ar.payload
  ) OR EXISTS (
    SELECT 1
    FROM public.operational_archive_rows ar
    JOIN public.scheduled_transport_requests r ON r.id = ar.source_id
    WHERE ar.archive_id = _archive_id
      AND ar.source_type = 'scale_change'
      AND to_jsonb(r) IS DISTINCT FROM ar.payload
  ) THEN
    RAISE EXCEPTION 'Há registros alterados após a preparação. Prepare novamente antes de finalizar.';
  END IF;

  DELETE FROM public.overtime_requests r
  USING public.operational_archive_rows ar
  WHERE ar.archive_id = _archive_id
    AND ar.source_type = 'overtime'
    AND r.id = ar.source_id
    AND r.worksite_id = v_archive.worksite_id;
  GET DIAGNOSTICS v_overtime = ROW_COUNT;

  DELETE FROM public.scheduled_transport_requests r
  USING public.operational_archive_rows ar
  WHERE ar.archive_id = _archive_id
    AND ar.source_type = 'scale_change'
    AND r.id = ar.source_id
    AND r.worksite_id = v_archive.worksite_id;
  GET DIAGNOSTICS v_scale = ROW_COUNT;

  IF v_overtime <> v_archive.overtime_count OR v_scale <> v_archive.scale_change_count THEN
    RAISE EXCEPTION 'A quantidade conferida não corresponde à quantidade removida.';
  END IF;

  DELETE FROM public.scheduled_transport_batches b
  WHERE b.worksite_id = v_archive.worksite_id
    AND NOT EXISTS (
      SELECT 1 FROM public.scheduled_transport_requests r WHERE r.batch_id = b.id
    );

  UPDATE public.operational_archives
  SET status = 'finalized', finalized_by = auth.uid(), finalized_at = now()
  WHERE id = _archive_id;

  RETURN QUERY SELECT v_overtime, v_scale;
END;
$function$;

REVOKE ALL ON FUNCTION public.finalize_operational_archive(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.finalize_operational_archive(uuid) TO authenticated;
